[2021-09-29 16:16:57,658] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test-05.change_decimal 2021-09-29T19:09:50.642199+00:00 [queued]>
[2021-09-29 16:16:57,665] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test-05.change_decimal 2021-09-29T19:09:50.642199+00:00 [queued]>
[2021-09-29 16:16:57,665] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-09-29 16:16:57,666] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2021-09-29 16:16:57,666] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-09-29 16:16:57,680] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): change_decimal> on 2021-09-29T19:09:50.642199+00:00
[2021-09-29 16:16:57,682] {standard_task_runner.py:54} INFO - Started process 49328 to run task
[2021-09-29 16:16:57,726] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'test-05', 'change_decimal', '2021-09-29T19:09:50.642199+00:00', '--job_id', '107', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/test05.py', '--cfg_path', '/tmp/tmp63jjxdqq']
[2021-09-29 16:16:57,726] {standard_task_runner.py:78} INFO - Job 107: Subtask change_decimal
[2021-09-29 16:16:57,870] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: test-05.change_decimal 2021-09-29T19:09:50.642199+00:00 [running]> alunoigti-VirtualBox
[2021-09-29 16:16:57,878] {taskinstance.py:1150} ERROR - [Errno 2] No such file or directory: '/home/alunoigti/airflow/data/3.DADOS/microdados_enade_2019.txt'
Traceback (most recent call last):
  File "/home/alunoigti/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/alunoigti/anaconda3/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/alunoigti/anaconda3/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/alunoigti/airflow/dags/test05.py", line 72, in change_decimal
    text = open(ORIGINAL_FILE, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/alunoigti/airflow/data/3.DADOS/microdados_enade_2019.txt'
[2021-09-29 16:16:57,881] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=test-05, task_id=change_decimal, execution_date=20210929T190950, start_date=20210929T191657, end_date=20210929T191657
[2021-09-29 16:17:02,654] {local_task_job.py:102} INFO - Task exited with return code 1
